#
# $Id: Makefile.am,v 1.3 2007/02/21 21:26:35 skimo Exp $
# Modified: Vincent Loechner, 2025
#

TEST_EXE = $(top_builddir)/polytest
TEST_FILES =  \
	convex1.in \
	convex2.in \
	gauss1.in \
	herve.in \
	simpl1.in \
	simpl2.in \
	simpl3.in \
	simpl4.in \
	simpl5.in \
	simpl6.in \
	simpl7.in \
	simpl8.in \
	simpl9.in \
	test1.in


include ../Tests.mk
