[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "pypolylib"
version = "6.01"
description = "Python bindings for PolyLib"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "scipy",
    "pyvista",
]

[tool.scikit-build]
wheel.packages = []
