#
# $Id: Makefile.am,v 1.2 2005/10/20 11:35:25 verdoolaege Exp $
# Modified: Vincent Loechner, 2025
#

TEST_EXE = $(top_builddir)/Zpolytest
TEST_FILES_32 =  \
	LatDiff1.in \
	LatDiff2.in \
	LatDiff3.in \
	LatDiff3b.in \
	LatDiff5.in \
	LatDiff7.in \
	LatDiff7b.in \
	LatDiff8.in \
	LatDiff8b.in \
	LatHNF1.in \
	LatHNF2.in \
	LatHNF3.in \
	LatInc1.in \
	LatInc2.in \
	LatInc3.in \
	LatInter1.in \
	LatInter1b.in \
	LatInter2.in \
	LatInter4.in \
	LatInter5.in \
	LatInter6.in \
	LatInter7.in \
	ZAlloc1.in \
	ZAlloc1b.in \
	ZAlloc1c.in \
	ZAlloc2.in \
	ZAlloc3.in \
	ZComp3.in \
	ZComp11.in \
	ZDiff1.in \
	ZDiff2.in \
	ZDiff3.in \
	ZDiff4.in \
	ZDiff5.in \
	ZDiff6.in \
	ZDiff7.in \
	ZDiff8.in \
	ZDiff9.in \
	ZDiff10.in \
	ZDiff12.in \
	ZDomain3.in \
	ZEmpty2.in \
	ZImage1.in \
	ZImPre1.in \
	ZImPre2.in \
	ZImPre3.in \
	ZInter1.in \
	ZInter2.in  \
	ZInter3.in  \
	ZPre1.in \
	ZPre2.in  \
	ZPre3.in \
	ZUnion1.in \
	ZUnion2.in


# 32 bits overflow in those:
TEST_FILES = $(TEST_FILES_32) \
	ZDiff11.in \
	ZDiff11b.in \
	ZDomain11.in


include ../Tests.mk
