#
# $Id: Makefile.am,v 1.2 2005/10/20 11:35:25 verdoolaege Exp $
# Modified: Vincent Loechner, 2025
#

TEST_EXE = $(top_builddir)/pp
TEST_FILES =  \
	c6.in \
	salvatore.in \
	salvatore_new1.in \
	salvatore_new2.in \
	xavi.in \
	ray1.in \
	ray2.in \
	ray3.in

# this one is pretty long...
#	c7.in \
#

# check those
#	c5.in \
#	c4.in \
#	c9.in
#	c10.in

include ../Tests.mk
